name: SmartSpawner
version: '${version}'
main: com.smartspawner.SmartSpawner
api-version: '1.21'
description: SmartSpawner plugin
author: Nighter
folia-supported: true

permissions:
  smartspawner.command.give:
    description: Use /smartspawner give to hand out spawners
    default: op
